# Integration with GitHub Actions
# See https://pre-commit.ci/
ci:
  autofix_prs: false
  autoupdate_schedule: monthly

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-merge-conflict
